### ISSUE TITLE
Watermark Video Not Save.

### ISSUE THREAD

**Issue by DhebaRam** [ededin/video_watermark#5]
**Watermark video not save in storage**

Video conversion completed
Video save failed

**Comment by ededin** [comment]
Please share some code snippet.

**Comment by RaminBgrn** [comment]
same issue 

my logs :
-----------
I/flutter (14108): Video conversion completed
I/flutter (14108): Video save failed
I/flutter (14108): device path is : /data/user/0/com.example.watermark_test/app_flutter
I/flutter (14108): on save path is : null
----------
my code : 

class Home extends StatelessWidget {
  Home({super.key});

  String _path = '';

  Future<void> getPath() async {
    Directory dir = await getApplicationDocumentsDirectory();
    _path = dir.path;
  }

  @override
  Widget build(BuildContext context) {
    getPath();
    VideoWatermark videoWatermark = VideoWatermark(
        sourceVideoPath: "videos/my_video.mp4",
        watermark: Watermark(
          image: WatermarkSource.file('images/splash_logo.png'),
          opacity: 0.5,
          watermarkAlignment: WatermarkAlignment.center,
          watermarkSize: WatermarkSize(150, 200),
        ),
        savePath: _path,
        onSave: (path) {
          print("device path is : $_path");
          print("on save path is : $path");
        });
    return SizedBox(
      child: ElevatedButton(
        child: Text('generate new videos'),
        onPressed: () async {
          await videoWatermark.generateVideo();
        },
      ),
    );
  }
}

**Comment by ededin** [comment]
Please specify the full local path of the source file something like `/data/user/0/images/splash_logo.png`.

**Comment by ededin** [comment]
If you are facing the same issue. Please try using latest version`1.0.5` or `1.0.5-LTS`

**Comment by RaminBgrn** [comment]
it made no difference

log :

`I/flutter (18635): Video conversion completed
I/flutter (18635): Video save failed
I/flutter (18635):  save path : null`

code : 

`  void makeWatermarkVideo() {
    Watermark myWaterMark = Watermark(
      image: WatermarkSource.asset('images/splash_logo.png'),
      opacity: 0.1,
      watermarkAlignment: WatermarkAlignment.center,
    );

    _watermark = VideoWatermark(
      sourceVideoPath: 'https://192.168.10.253/video/my_video.mp4',
      watermark: myWaterMark,
      progress: ((value) => print(value)),
      onSave: (saveValue) {
        print(" save path : $saveValue");
      },
    );
  }`

**Comment by RaminBgrn** [comment]
it works for me ...
thank you

**Comment by ededin** [comment]
Thans for your support @RaminBgrn
