### ISSUE TITLE
Can you update ffmpeg_kit_flutter_min library in your pubspec.yaml to another version, without -LTS?

### ISSUE THREAD

**Issue by thang510023** [ededin/video_watermark#6]
![image](https://user-images.githubusercontent.com/26160656/209448112-35945104-2d46-43b9-86a8-62526c51eca3.png)
![image](https://user-images.githubusercontent.com/26160656/209448178-3f53eeed-a557-4c73-8684-2773d12894d1.png)

**Comment by ededin** [comment]
Thanks for your valuable feedback. We have released non LTS version as per your request. Please try `v1.0.5`. If LTS version needed use `v1.0.5-LTS`.
